# Generated by Django 5.0.4 on 2025-10-02 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_profiles_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
