# Generated by Django 5.0.4 on 2025-10-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_profiles_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profiles',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
