# Generated by Django 5.0.4 on 2025-10-02 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_profiles_about_profiles_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('employment_type', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Self-employed', 'Self-employed'), ('Internship', 'Internship'), ('Trainee', 'Trainee')], default='Internship', max_length=250)),
                ('company', models.CharField(blank=True, max_length=250, null=True)),
                ('current_company', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(blank=True, max_length=250, null=True)),
                ('skills', models.TextField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.profiles')),
            ],
        ),
    ]
