# Generated by Django 5.0.4 on 2025-10-02 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_addexperience'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='joined_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
