# Generated by Django 5.0.4 on 2025-10-02 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_profiles_joined_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='joined_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
