# Generated by Django 5.0.4 on 2025-10-04 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_profiles_joined_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='image',
            field=models.ImageField(default='user.png', upload_to=''),
        ),
    ]
