# Generated by Django 5.0.4 on 2025-10-08 19:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_relationshipmanager_relationship'),
        ('post', '0015_alter_like_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='company',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='joined_on',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='role',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='profiles',
            index=models.Index(fields=['role'], name='account_pro_role_09c6a8_idx'),
        ),
        migrations.AddIndex(
            model_name='profiles',
            index=models.Index(fields=['company'], name='account_pro_company_859266_idx'),
        ),
        migrations.AddIndex(
            model_name='profiles',
            index=models.Index(fields=['joined_on'], name='account_pro_joined__4661cc_idx'),
        ),
    ]
