# Generated by Django 5.0.4 on 2025-10-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_profiles_company_alter_profiles_joined_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='status',
            field=models.CharField(choices=[('send', 'send'), ('accepted', 'accepted')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterUniqueTogether(
            name='relationship',
            unique_together={('sender', 'receiver')},
        ),
        migrations.AddIndex(
            model_name='relationship',
            index=models.Index(fields=['sender', 'status'], name='account_rel_sender__b27b36_idx'),
        ),
        migrations.AddIndex(
            model_name='relationship',
            index=models.Index(fields=['receiver', 'status'], name='account_rel_receive_7ad845_idx'),
        ),
        migrations.AddIndex(
            model_name='relationship',
            index=models.Index(fields=['created'], name='account_rel_created_2014ac_idx'),
        ),
    ]
