# Generated by Django 5.0.4 on 2025-10-02 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_alter_posts_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
