# Generated by Django 5.0.4 on 2025-10-07 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_alter_posts_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_on']},
        ),
    ]
