# Generated by Django 5.0.4 on 2025-10-08 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_alter_comment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='reposted_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='post.posts'),
        ),
        migrations.AddField(
            model_name='posts',
            name='total_repost',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
