# Generated by Django 5.0.4 on 2025-10-08 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_posts_reposted_from_posts_total_repost'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='is_repost',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='posts',
            name='original_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reposts', to='post.posts'),
        ),
    ]
