# Generated by Django 5.0.4 on 2025-10-08 19:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_posts_is_repost_posts_original_post'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='created_on',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='is_repost',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='posts',
            name='total_repost',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddIndex(
            model_name='posts',
            index=models.Index(fields=['author', 'created_on'], name='post_posts_author__52b499_idx'),
        ),
        migrations.AddIndex(
            model_name='posts',
            index=models.Index(fields=['is_repost', 'created_on'], name='post_posts_is_repo_6494c8_idx'),
        ),
    ]
