# Generated by Django 5.0.4 on 2025-10-09 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0015_alter_like_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set(),
        ),
    ]
