# Generated by Django 5.0.4 on 2025-10-15 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0016_alter_like_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='status',
            field=models.CharField(choices=[('public', 'public'), ('friend', 'friend'), ('me', 'me')], default='public', max_length=10),
        ),
    ]
