# Generated by Django 5.0.4 on 2025-10-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0017_posts_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='status',
            field=models.CharField(choices=[('public', 'public'), ('friend', 'friend'), ('me', 'me')], db_index=True, default='public', max_length=10),
        ),
    ]
